services:
  db:
    image: postgres:latest
#    restart: "no"
    ports:
      - '27017'
      - "5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres_secret
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  db_volume:
